### ISSUE TITLE
en has 4.5A1.pdf, 4.6A1.pdf, but sv hasn’t

### ISSUE THREAD

**Issue by jim1001** [jim1001/DemPower-Issues#100]
Reena & Therese to ensure the app has the same files for both sv & en versions. (although the content in those files can, of course, be different!)

**Comment by thebi84** [comment]
Done now

**Comment by jim1001** [comment]
Thanks Therese ! - that worked well :) 
I will test in the _sv version then update the issue.

**Comment by jim1001** [comment]
Done. You should install the latest `sv `app version to see. Until further notice the latest version will always be in this folder:
`Dropbox (The University of Manchester)\DemPower_app_install\sv
`and will be called `DemPower_sv_<version_number>.apk`

You also need to copy the PDFs from DropBox to your tablet, i.e. 
from 
`Dropbox (The University of Manchester)\DemPower_app_install\sv\DemPowerIO\In\PDFs\Activities `
to
`<Tablet Internal Storage>/\DemPowerIO\In\PDFs\Activities`

As said before, I suggest keeping one tablet for the `_en` app and one for the `_sv` app otherwise it will get confusing! Therese - let me know if you need help setting up another tablet.
