### ISSUE TITLE
Supply music files

### ISSUE THREAD

**Issue by jim1001** [jim1001/DemPower-Issues#102]
Supply music files in same format as other audio in app, i.e. m4a files produced using Codec MPEG AAC Audio (mp4a)

**Comment by jim1001** [comment]
Jim to choose 10 - 15 tracks up to  £10 value for 1.4 Activity 2 & pay with Google Play voucher

**Comment by jim1001** [comment]
10 tunes chosen & uploaded to DropBox. Tested with DemPower UK version.

**Comment by thebi84** [comment]
These 10 tunes works for the swedish version as well:)

**Comment by jim1001** [comment]
Customers happy so closing issue.
