### ISSUE TITLE
Further information and Evaluation buttons on Home screen - where to?

### ISSUE THREAD

**Issue by jim1001** [jim1001/DemPower-Issues#111]
We have buttons for these on the Home screen.  Where should they lead?  
Further information could lead to screen with links to more PDFs
Evaluation could lead to screen  with view-only evaluation questions
These are only ideas!

**Comment by jim1001** [comment]
Added cards / screens for these two items. New _en app version uploaded to DropBox. Waiting for researchers to decide what text / links screens should contain.

**Comment by lasradoreena** [comment]
Please upload the evaluation questionnaires from the following link.
https://www.dropbox.com/sh/z04de2fjlzlxiax/AAAUuGv3deRBVdh1vMzRI1uSa?dl=0

Further info scree as discussed today

**Comment by jim1001** [comment]
App Further information screen will display a link to each chapter's Further information screen, i.e
Chapter 1 Further information
Chapter 2 Further information
Chapter 3 Further information
Chapter 4 Further information

**Comment by jim1001** [comment]
Split into two new issues: 126 & 127
