### ISSUE TITLE
Decide what to do with activity 2.5A1

### ISSUE THREAD

**Issue by jim1001** [jim1001/DemPower-Issues#123]
From issue 108

> 2.5A1- May be its best to get rid of the ‘g to activity’ button here and ave another box following the activity box with instructions on how to go to the games folder on the tablet. Jim, you might have other thoughts feel free to make suggestions

Two suggestions:

1. you create a PDF with instructions & the Go to button opens that
2. you create a Help video with instructions and the Go to button goes to the Help screen with that option selected

**Comment by lasradoreena** [comment]
Happy with the second option

**Comment by jim1001** [comment]
Reena, Therese - I've looked at this again.

Don't think users will want to be taken to the Help every time they tap the Go to activity button. Maybe only the first time. 

For this reason I think it will be better to remove the "Go to activity" button and add at end of activity text box "See the 'How to... Play games' video on Help screen if required".  This is similar to what you said at the top.  Extra text won't be spoken of course.

What do you think?

**Comment by thebi84** [comment]
It sound good Jim
