### ISSUE TITLE
Include Disclaimer statement in DemPower

### ISSUE THREAD

**Issue by jim1001** [jim1001/DemPower-Issues#159]
Reena to write.
Jim to put on _About_ screen.

**Comment by lasradoreena** [comment]
I am not sure how to do this or even we require this. 

Potential info to include:
The information provided within the app is based on available research evidence and other data available over the internet as of March 2018

The project is funded by ESRC & NIHR, conducted by University of Manchester & Linkoping University, Sweden

**Comment by jim1001** [comment]
OK, on About screen I could append:

> Disclaimer
> 
> The information provided within the app is based on available research evidence and other data available over the internet as of March 2018. The project is funded by ESRC & NIHR, conducted by University of Manchester & Linkoping University, Sweden.

That doesn't sound like a disclaimer to me but let me know here what you want.

**Comment by jim1001** [comment]
Reena suggests changing the About page to:

# About

The information provided within DemPower is based on available research evidence and other data available over the internet as of March 2018. The project is funded by ESRC & NIHR and conducted by the University of Manchester and Linköping University, Sweden. 

Then for Swedish version:

## Guide authors 
Therése Bielsten, Reena Lasrado, Ingrid Hellström

and for English version:

## Guide authors 
Reena Lasrado, Therése Bielsten, Ingrid Hellström

then **App developer, Version** as now


Hope OK with you Therese!
