### ISSUE TITLE
Text response: Add message in text box on how to save

### ISSUE THREAD

**Issue by jim1001** [jim1001/DemPower-Issues#161]
Can add a message to box each time a new response is started, something like :

> When finished editing, remove the keyboard using the tablet back button.
> Tap the Save button, now enabled,  to save your response.
> See Help video for more information.

Users can delete this of course when editing their response, but could improve usability.

Text response activities for testing:
1.4 Activity 1

Reena - do you want this modification?

**Comment by lasradoreena** [comment]
Yes Jim, Please do so if possible.
