### ISSUE TITLE
Convert _sv Evaluation docs from Word to PDF & rename to match _en install PDFs

### ISSUE THREAD

**Issue by jim1001** [jim1001/DemPower-Issues#164]
Word docs [here](https://www.dropbox.com/sh/liz8f1c08g8vgll/AAB03DSaD2WgKndiT2-PvcN6a?dl=0)

**Comment by jim1001** [comment]
Done - uploaded to [DropBox folder](https://www.dropbox.com/sh/oq23lvpxhku2fyk/AABIPGhCXCjoykz-LxE1owEPa?dl=0) & tested on tablet. Note - Ch3 doc contains comments which show in converted PDF.

**Comment by jim1001** [comment]
Therese - are you happy with this? Are you going to change Ch3 doc?

**Comment by thebi84** [comment]
Yes!
Changed the Ch3 now

Från: jim1001 <notifications@github.com<mailto:notifications@github.com>>
Svara till: jim1001/DemPower-Issues <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: lördag 28 april 2018 23:13
Till: jim1001/DemPower-Issues <DemPower-Issues@noreply.github.com<mailto:DemPower-Issues@noreply.github.com>>
Kopia: Therese Bielsten <therese.bielsten@liu.se<mailto:therese.bielsten@liu.se>>, Assign <assign@noreply.github.com<mailto:assign@noreply.github.com>>
Ämne: Re: [jim1001/DemPower-Issues] Convert _sv Evaluation docs from Word to PDF & rename to match _en install PDFs (#164)


Therese - are you happy with this? Are you going to change Ch3 doc?

**Comment by jim1001** [comment]
Looks fine now - changed [file ](https://www.dropbox.com/s/i2a5zvou51oztms/Ch3.pdf?dl=0)on DropBox.

**Comment by jim1001** [comment]
No further comments received so closing the issue.
