### ISSUE TITLE
Make _sv Help videos

### ISSUE THREAD

**Issue by jim1001** [jim1001/DemPower-Issues#167]
> I have uploaded some help videos today. If there is english text showing on the screen I have told that all the text will be in Swedish. Do you think that will work?

Therese - is this question still valid?  

I've had a look at your videos.

They need to be 508 pixels wide by 862 pixels high to fit the app (and .webm encoded formats but I can convert for you). If you look at the _en ones you'll see I didn't include the top bar of the SideSync screen so videos look like what the users see as close as possible.  I did that with my Windows capture software.

I suggest getting one right before producing more ;-)

**Comment by thebi84** [comment]
No, I remade the ones that was showing english text.
I would really appreciate if you can convert for me.
Ok, I will look into that.

About the manual (text), I have uploaded the swedish translation in comments. I can´t do a new one. Can you do the screens/pictures? If so, I can fill in the swedish text.

**Comment by jim1001** [comment]
> About the manual (text), I have uploaded the swedish translation in comments. I can´t do a new one. Can you do the screens/pictures? If so, I can fill in the swedish text.

Perhaps it would make more sense if you talk to Reena about the paper manual as she produced the screens/pictures for the English one. I've assigned her to this task now.


> I would really appreciate if you can convert for me.
> Ok, I will look into that.

I'm not sure what you want converting and what you are looking into. Please can you explain? Thanks!

**Comment by thebi84** [comment]
Therese - is this question still valid?

I've had a look at your videos.

They need to be 508 pixels wide by 862 pixels high to fit the app (and .webm encoded formats but I can convert for you). If you look at the _en ones you'll see I didn't include the top bar of the SideSync screen so videos look like what the users see as close as possible. I did that with my Windows capture software.

I suggest getting one right before producing more ;-)

Från: jim1001 <notifications@github.com<mailto:notifications@github.com>>
Svara till: jim1001/DemPower-Issues <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: tisdag 24 april 2018 18:13
Till: jim1001/DemPower-Issues <DemPower-Issues@noreply.github.com<mailto:DemPower-Issues@noreply.github.com>>
Kopia: Therese Bielsten <therese.bielsten@liu.se<mailto:therese.bielsten@liu.se>>, Assign <assign@noreply.github.com<mailto:assign@noreply.github.com>>
Ämne: Re: [jim1001/DemPower-Issues] Make _sv Help videos (#167)


Assigned #167<https://github.com/jim1001/DemPower-Issues/issues/167> to @thebi84<https://github.com/thebi84>.

**Comment by thebi84** [comment]
Convert videos to fit the app :)
Look into how to not include top screen in side sync and I think I got it now.

**Comment by jim1001** [comment]
> Convert videos to fit the app :)
> Look into how to not include top screen in side sync and I think I got it now.

Right - but if you are making the videos again then I won't convert the old ones. Can you just produce one of the right size without the top band ( I can convert from mov / mp4 / etc to webm). We can get that working in DemPower. Once we are happy with that then you can go on to produce the rest...

**Comment by thebi84** [comment]
I am not planning to make the videos again. All help videos are done now and the new videos that I uploaded today are without the top band.

**Comment by jim1001** [comment]
I think you are trying to test me :-)

With a bit of wizardry these now work in the app and all look like they were made to a standard.

`DemPower_app_install\sv\DemPowerIO\In\Videos\Help`

One was missing - "Use blue text"

_How do we use it_ is _0.3.mp4_ in this folder:
`DemPower_app_install\sv\DemPowerIO\In\Videos\Introduction`

**Comment by thebi84** [comment]
No ;-) I am just a bit tired of it and I can imagine you are as well...:)

**Comment by thebi84** [comment]
Thanks, it looks good!

**Comment by jim1001** [comment]
Closing issue as customer is happy.
