### ISSUE TITLE
_sv Communication video 4.6C1 re-processed to fill frame

### ISSUE THREAD

**Issue by jim1001** [jim1001/DemPower-Issues#169]
Therese,

I've re-processed a 20s sample of your video so that it now fills the frame. 

[Original](https://www.dropbox.com/s/qq2f5yda4vzfqi3/4.6C1_orig.webm?dl=0) (~ 20 MB)
[New sample](https://www.dropbox.com/s/3akjc3ee3ves6q1/4.6C1.webm?dl=0) (~ 730 KB)

I think it looks better. Download to your tablet  and have a look. The file named _4.6C1.webm_ on your tablet is the one that _DemPower_ will show.

If you think it's better I will process the full video.

**Comment by thebi84** [comment]
Thanks, yes it looks better.

**Comment by jim1001** [comment]
OK, thanks, I'll process the whole video like this now & let you know when complete.

**Comment by jim1001** [comment]
[Full video](https://www.dropbox.com/s/3akjc3ee3ves6q1/4.6C1.webm?dl=0) now processed & can be uploaded to your tablet.

**Comment by jim1001** [comment]
It looks OK on my tablet. Had no comments so closing the issue.
